{"name": "test_registerAccount", "status": "broken", "statusDetails": {"message": "IndexError: single positional indexer is out-of-bounds", "trace": "self = <scripts.test_registerAccount.Test_registerAccount object at 0x0000020462CA6518>\n\n    def test_registerAccount(self):\n        self.page.login().click_phone_login()                                                                           # 点击手机号登录\n        self.page.login_phone().input_phone(str(phone))                                                                 # 输入手机号\n        #self.page.login_phone().back()                                                                                  # 关小键盘\n        self.page.login_phone().click_getCaptcha()                                                                      # 点击获取验证码按钮\n        captcha = pd.read_sql('select captcha FROM t_captcha WHERE phone = \"' + str(phone) + '\" order by postTime desc',engine)\n>       captcha = captcha.iloc[0, 0]                                                                                    # 正式服数据库拿验证码\n\ntest_registerAccount.py:37: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nd:\\python\\lib\\site-packages\\pandas\\core\\indexing.py:1472: in __getitem__\n    return self._getitem_tuple(key)\nd:\\python\\lib\\site-packages\\pandas\\core\\indexing.py:2013: in _getitem_tuple\n    self._has_valid_tuple(tup)\nd:\\python\\lib\\site-packages\\pandas\\core\\indexing.py:222: in _has_valid_tuple\n    self._validate_key(k, i)\nd:\\python\\lib\\site-packages\\pandas\\core\\indexing.py:1957: in _validate_key\n    self._validate_integer(key, axis)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pandas.core.indexing._iLocIndexer object at 0x000002046AD6E188>, key = 0\naxis = 0\n\n    def _validate_integer(self, key, axis):\n        # return a boolean if we have a valid integer indexer\n    \n        ax = self.obj._get_axis(axis)\n        l = len(ax)\n        if key >= l or key < -l:\n>           raise IndexError(\"single positional indexer is out-of-bounds\")\nE           IndexError: single positional indexer is out-of-bounds\n\nd:\\python\\lib\\site-packages\\pandas\\core\\indexing.py:2009: IndexError"}, "start": 1579290423503, "stop": 1579290438247, "uuid": "5652f02c-d7e3-45be-ac49-65f3ad8a941d", "historyId": "9083d42b8698837b487d9edccb601c98", "testCaseId": "2ce719bf97fd59efd8cc9702df81acad", "fullName": "test_registerAccount.Test_registerAccount#test_registerAccount", "labels": [{"name": "suite", "value": "test_registerAccount"}, {"name": "subSuite", "value": "Test_registerAccount"}, {"name": "host", "value": "PV-X00232293"}, {"name": "thread", "value": "12788-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_registerAccount"}]}