{"name": "test_registerAccount", "status": "broken", "statusDetails": {"message": "IndexError: single positional indexer is out-of-bounds", "trace": "self = <scripts.test_001_registerAccount.Test_registerAccount object at 0x00000292CB005208>\n\n    def test_registerAccount(self):\n        with allure.step('第一次打开Timing需要预处理'):\n            result = self.page.login().check_fristPage()\n            if result == False:\n                with allure.step('用户当前已完成授权'):\n                    pass\n            else:\n                with allure.step('用户当前未授权'):\n                    time.sleep(2)\n                    self.page.login().check_location()\n                    if result == False:\n                        with allure.step('用户当前已同意定位'):\n                            pass\n                    else:\n                        with allure.step('用户当前未授权定位'):\n                            self.page.login().click_allowLocation()\n                    self.page.login().click_agree()\n                    time.sleep(5)\n                    self.page.login().click_ignore()\n                    time.sleep(2)\n            with allure.step('点击手机号登录'):\n                self.page.login().click_phone_login()\n            with allure.step('查询尚未注册的手机号并填入'):\n                ID = \"1\"\n                Phone = phone\n                while len(ID) == 1:\n                    Phone = Phone + 1\n                    ID = pd.read_sql('SELECT ID FROM t_user where phone=\"' + str(Phone) + '\" ', engine)\n                self.page.login_phone().input_phone(str(Phone))\n            with allure.step('点击获取验证码按钮'):\n                self.page.login_phone().click_getCaptcha()\n                time.sleep(2)\n            with allure.step('从数据库拿验证码'):\n                captcha = pd.read_sql(\n                    'select captcha FROM t_captcha WHERE phone = \"' + str(Phone) + '\" order by postTime desc', engine)\n>               captcha = captcha.iloc[0, 0]\n\ntest_001_registerAccount.py:64: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nd:\\python\\lib\\site-packages\\pandas\\core\\indexing.py:1472: in __getitem__\n    return self._getitem_tuple(key)\nd:\\python\\lib\\site-packages\\pandas\\core\\indexing.py:2013: in _getitem_tuple\n    self._has_valid_tuple(tup)\nd:\\python\\lib\\site-packages\\pandas\\core\\indexing.py:222: in _has_valid_tuple\n    self._validate_key(k, i)\nd:\\python\\lib\\site-packages\\pandas\\core\\indexing.py:1957: in _validate_key\n    self._validate_integer(key, axis)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pandas.core.indexing._iLocIndexer object at 0x00000292CB0C6DB8>, key = 0\naxis = 0\n\n    def _validate_integer(self, key, axis):\n        # return a boolean if we have a valid integer indexer\n    \n        ax = self.obj._get_axis(axis)\n        l = len(ax)\n        if key >= l or key < -l:\n>           raise IndexError(\"single positional indexer is out-of-bounds\")\nE           IndexError: single positional indexer is out-of-bounds\n\nd:\\python\\lib\\site-packages\\pandas\\core\\indexing.py:2009: IndexError"}, "steps": [{"name": "第一次打开Timing需要预处理", "status": "broken", "statusDetails": {"message": "IndexError: single positional indexer is out-of-bounds\n", "trace": "  File \"D:\\jenkins\\workspace\\Timing\\scripts\\test_001_registerAccount.py\", line 64, in test_registerAccount\n    captcha = captcha.iloc[0, 0]\n  File \"d:\\python\\lib\\site-packages\\pandas\\core\\indexing.py\", line 1472, in __getitem__\n    return self._getitem_tuple(key)\n  File \"d:\\python\\lib\\site-packages\\pandas\\core\\indexing.py\", line 2013, in _getitem_tuple\n    self._has_valid_tuple(tup)\n  File \"d:\\python\\lib\\site-packages\\pandas\\core\\indexing.py\", line 222, in _has_valid_tuple\n    self._validate_key(k, i)\n  File \"d:\\python\\lib\\site-packages\\pandas\\core\\indexing.py\", line 1957, in _validate_key\n    self._validate_integer(key, axis)\n  File \"d:\\python\\lib\\site-packages\\pandas\\core\\indexing.py\", line 2009, in _validate_integer\n    raise IndexError(\"single positional indexer is out-of-bounds\")\n"}, "steps": [{"name": "用户当前未授权", "status": "passed", "steps": [{"name": "用户当前未授权定位", "status": "passed", "start": 1586855768476, "stop": 1586855771615}], "start": 1586855766459, "stop": 1586855779212}, {"name": "点击手机号登录", "status": "passed", "start": 1586855779212, "stop": 1586855779784}, {"name": "查询尚未注册的手机号并填入", "status": "passed", "start": 1586855779784, "stop": 1586855786063}, {"name": "点击获取验证码按钮", "status": "passed", "start": 1586855786063, "stop": 1586855788816}, {"name": "从数据库拿验证码", "status": "broken", "statusDetails": {"message": "IndexError: single positional indexer is out-of-bounds\n", "trace": "  File \"D:\\jenkins\\workspace\\Timing\\scripts\\test_001_registerAccount.py\", line 64, in test_registerAccount\n    captcha = captcha.iloc[0, 0]\n  File \"d:\\python\\lib\\site-packages\\pandas\\core\\indexing.py\", line 1472, in __getitem__\n    return self._getitem_tuple(key)\n  File \"d:\\python\\lib\\site-packages\\pandas\\core\\indexing.py\", line 2013, in _getitem_tuple\n    self._has_valid_tuple(tup)\n  File \"d:\\python\\lib\\site-packages\\pandas\\core\\indexing.py\", line 222, in _has_valid_tuple\n    self._validate_key(k, i)\n  File \"d:\\python\\lib\\site-packages\\pandas\\core\\indexing.py\", line 1957, in _validate_key\n    self._validate_integer(key, axis)\n  File \"d:\\python\\lib\\site-packages\\pandas\\core\\indexing.py\", line 2009, in _validate_integer\n    raise IndexError(\"single positional indexer is out-of-bounds\")\n"}, "start": 1586855788816, "stop": 1586855788908}], "start": 1586855765689, "stop": 1586855788908}], "start": 1586855765689, "stop": 1586855788909, "uuid": "6354ae2d-5bf4-46f1-850c-10875c817469", "historyId": "70208ecb89cae63421bdb3a7ce67b14a", "testCaseId": "99d025376bb24dd8261c1137c8f8bab7", "fullName": "test_001_registerAccount.Test_registerAccount#test_registerAccount", "labels": [{"name": "suite", "value": "test_001_registerAccount"}, {"name": "subSuite", "value": "Test_registerAccount"}, {"name": "host", "value": "PV-X00232293"}, {"name": "thread", "value": "109132-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_001_registerAccount"}]}